sudo: required
dist: trusty
language: python
python:
  - 2.7
before_install:
  - sudo add-apt-repository ppa:free.ekanayaka/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install phantomjs -y
install: make build
script: make test
